### ISSUE TITLE
Todo App 요구사항 명세서 작성

### ISSUE THREAD

**Issue by tapdancedorong** [tapdancedorong/TodoApp#1]
### 목적
: API 계층 구현

### 해당 기능을 구현하기 위해 할 일
1. [ ] Controller 클래스 구현
2. [ ] DTO 클래스 구현
3. [ ] DTO 유효성 검증

### 예상 작업 시간
: 3h
